import os
import glob
import re

js_files = glob.glob('js/admin-*.js')

for filepath in js_files:
    with open(filepath, 'r') as f:
        content = f.read()

    # If this file has broken filter code generated by a previous process:
    # "const pillsContainer_... = document.getElementById('pills-...');"
    # We remove these lines.
    
    content = re.sub(r'const pillsContainer_[^\n]*\n', '', content)
    content = re.sub(r'const btns_filterPillsContainer[^\n]*\n', '', content)
    
    # We replace any occurrences of:
    # const filterStatusSelect = document.getElementById('filter-status');
    # filterStatusSelect.addEventListener('change', ... )
    
    # Actually, it's safer to just inject a universal filter logic if not already present.
    # But wait, each file has its own rendering logic and variables (filterStatus, filterPriority, etc.)
    # Let's fix admin-amc.js syntax error first.
    if filepath.endswith('admin-amc.js'):
        content = content.replace('  });\n  });\n});', '  });\n});')

    with open(filepath, 'w') as f:
        f.write(content)

print("JS cleanup complete")
